.TH "pkgtxt2db" 1 "01/31/2012" "Frederic Galusik"


.SH NAME

.P
pkgtxt2db \- A perl utility to convert the Slackware PACKAGES.TXT to a database.

.P
Are supported: CSV, JSON

.SH SYNOPSIS

.P
\fBpkgtxt2db\fR [\fIOPTIONS\fR]

.SH DESCRIPTION

.P
\fBPkgtxt2db\fR is a tool for automoatically convert PACKAGES.TXT from this plain text format to a database one like CSV, JSON.

.SH GENERAL OPTIONS

.TP
\fB\-h\fR, \fB\-\-help\fR
Simple help

.TP
\fB\-v\fR, \fB\-\-version\fR
Print Pkgtxt2db version

.TP
\fB\-c\fR, \fB\-\-csv\fR
Convert PACKAGES.TXT to a CSV database.

.TP
\fB\-j\fR, \fB\-\-json\fR
Convert PACKAGES.TXT to a JSON database.

.TP
\fB\-t\fR, \fB\-\-target\fR
Choose between Slackware or Salix repositories.

It can be:

.RS
.IP \(bu 3
slack32: slackware i486 repository
.IP \(bu 3
slack64: slackware x86_64 repository
.IP \(bu 3
salix32: salix i486 repository
.IP \(bu 3
salix64: salix x86_64 repository

.RE

.TP
\fB\-r\fR, \fB\-\-release\fR
Choose the slackware or salix release.

It can be: current (if exist), 13.37, ...

.SH COMMAND LINE USAGE

.P
Here are some usages examples.

.TP
\fBpkgtxt2db \-c \-t slack32 \-r current\fR
It will fetch and convert PACKAGES.TXT from the Slackware current i486
repository to a CSV database (tab separated): \fIpkgtxt.csv\fR.
You can open it with libreoffice ;)

.TP
\fBpkgtxt2db \-j \-t salix64 \-r 13.37\fR
It will fetch and convert PACKAGES.TXT from the Salix 13.37 x86\-64
repository to a JSON database: \fIpkgtxt.json\fR.

.SH WEBSITE

.P
http://www.salixos.org/wiki/index.php/Pkgtxt2db

.SH AUTHOR

.P
Pkgtxt2db was written by Frederic Galusik <fredg~at~salixos~dot~org>

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man pkgtxt2db.t2t
